# PYTHON DATA SCIENCE HANDBOOK

## Chapter 4: Understanding Data Types in Python

In [1]:
import numpy as np

np.array([range(10)])

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [2]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.arange(0,20,2)  # starting at 0, ending at 20, stepping by 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.random.random((1,5)) # pseudorandom values between 0 and 1

array([[0.24259852, 0.90912611, 0.95938597, 0.75302343, 0.2665752 ]])

In [9]:
np.random.randint(0,10,(3,3)) # Create a 3x3 array of pseudorandom integers in the interval [0, 10)

array([[2, 1, 6],
       [8, 1, 4],
       [0, 6, 2]])

can specify the type with _dtype='int16'_ with string 

or 

or can specify type with _dtype=np.int16_ using numpy object